name: Build .NET WebAPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Sprawdzenie kodu
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Zainstalowanie .NET SDK
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      # 3. Przywrócenie zależności NuGet
      - name: Restore dependencies
        run: dotnet restore

      # 4. Budowanie projektu
      - name: Build project
        run: dotnet build --no-restore

      # 5. (Opcjonalnie) Uruchomienie testów
      - name: Run tests
        run: dotnet test --no-build --verbosity normal
